---
title: "R Notebook"
output:
  html_notebook: default
  html_document:
    df_print: paged
  pdf_document: default
---

# 1. §6.1 Modified #9.  Each of 150 newly manufactured items is examined, and the numberof scratches per item is recorded.  (The items are supposed to be free of scratches.)  Hereis the data:

## a. Find  an  unbiased  estimator  of \[\mu\] and  compute  the  estimate  for  the  data.   [Hint: E(X) =\[\mu\] forXPoisson, so E(X) = ?]  [Hint 2:You can see that “2” is the mostfrequent observed count, so your estimate for\[\mu\] should probably be pretty close to 2.]

$$
\lambda = \frac{\sum i*X_i}{n} = \frac{14*0+35*1+43*2+28*3+4*17+5*10+6*2+1*7}{150} = \frac{342}{150} = 2.28
$$
$$
E(\bar{X})=E(X) = \lambda=2.28
$$
## b. What is the standard deviation (standard error) of youur estimator?  Compute the estimated standard error. [Hint std^2 = mean for X]
For poisson distribution \[V(x) = \lambda = 2.28\], \[V(\bar{x}) = \frac{V(x)}{n} = \frac{2.28}{150} = 0.0152\]

# 2. 6.1 #11.  Of n1 randomly selected male smokers, X1 smoked filter cigarettes, whereasof n2 randomly  selected  female  smokers, X2 smoked  filter  cigarettes.   Let p1 and p2 denote the probabilities that a randomly selected male and femal,  respectively,  smokefilter cigarettes.

## a. Show that (X1/n1−X2/n2) is an unbiased estimator for p1 − p2.

$$
p_1 - p_2 = E(x_1)-E(x_2) = \frac{x_1}{n_1}-\frac{x_2}{n_2}
$$
## b. What is the standard error of the estimator in (a)?

$$
Var(p_1-p_2) = Var(p_1)+Var(P_2) = n_1p_1(1-p_1) +n_2p_2(1-p_2)
$$
$$
Standard Error =\sqrt{Var(p_1-p_2)} = \sqrt{n_1p_1(1-p_1) +n_2p_2(1-p_2)}
$$

## c. How would you use the observed values x1 and x2 to estimate the standard error of your estimator?

I would find p1 and p2 using \[p_i = \frac{x_i}{n_i}\]. And then plug into formula found in 2b.

## d. If n1 = n2 = 200,X1 = 127, and x2= 176, use the estimator of (a) to obtain a nestimate of p1−p2.

$$
p1−p2 = \frac{127}{200} -\frac{176}{200} = -0.245
$$

## e.  Use the result of part (c) and the data of part (d) to estimate the standard error ofthe estimator.
$$
p_1 = \frac{127}{200}=0.635
$$
$$
p_2 = \frac{176}{200} = 0.88
$$
$$
SE = \sqrt{200*0.635(1-0.635) + 200*0.88(1-0.88)} = 8.21
$$

# 3.  For each of the following estimators of mean if ...

## a.
\[\bar{X_5}\] is unbiased for \mu\] because normal distribution is symetric about the mean.

## b.
\[X_1-X_2+X_3-X_4+X_5\] is unbiased as \[X_n=X_{n+1}\],therefore everything except for one X cancels out.

## c.
$$
\frac{X_1+2X_2+3X_3+4X_4+5X_5}{15} = \frac{15X}{15} = X
$$
Therefore \[\frac{X_1+2X_2+3X_3+4X_4+5X_5}{15}\] is an unbiased estimate for \[\hat{\mu}\]

## d. 
\[1.01\bar{X}_5\] is not an unbiased estimate for \[\hat{\mu}\]. Standard error is 
$$
0.01*\bar{X}_5
$$

# 4. Let Xi =, i=1,2..n be  continuous  random  variables  with  pdf f(x) = {Theta}exp(-Theta x), x>0, We're given that Theta>0. The Xi's are independent.

## a. Find the Method of Moments estimator of Theta, Theta_mom

$$
E(X) = \int_0^\infty xf(x)dx = \int_0^\infty x\theta e^{-\theta x}dx = \frac{1}{\theta} = \bar{x}
$$
$$
\theta_{Mom} = \frac{1}{\bar{x}}
$$

## b. Is Theta_mom unbiased for Theta

Theta_mom is not an unbiased estimator as  1/E(X) != E(1/X).

## c. Find the likelihood function,L(θ).

$$
L(\theta) = \prod_{i=1}^n \theta e^{-\theta x_i} = \theta^n e^{\theta \sum_{i=1}^n x_i}
$$
## d. Find the Maximum Likelihood estimator of Theta, Theta_mle
$$
\ln \left(L(\theta)\right) = n\ln(\theta)+\theta \sum_{i=1}^n x_i
$$
$$
\frac{d\theta \ln L(\theta)}{dt} = \frac{n}{\theta}+\sum_{i=1}^n x_i = 0
$$
$$
\frac{n}{\theta} = -\sum_{i=1}^n x_i
$$
$$
\theta = \frac{n}{-\sum_{i=1}^n x_i}
$$

## e. Is Theta_mle unbiased for Theta

Is Theta_mle not an unbiased estimator as  1/E(X) != E(1/X)


# 5. Let Yi=Bernoulli (p) i=1,2,..n

## a.  Find the Method of Moments estimator ofp.
$$
E(Y_i) = p
$$
Therefore
$$
\bar{y_i} = p
$$

## b. Find the Maximum Likelihood Estimator of p
$$
L(p) = \prod_{i=1}^nB(p) = B(p)^n = \prod p^k(1-p)^{1-k}
$$
$$
\ln(L(p)) = \ln p\sum x_i+ln(1-p)\sum(1-x_i)
$$
$$
\frac{dp \ln(L(p))}{dt} = \frac{\sum x}{p}-\frac{\sum(1-x_i)}{1-p}=0
$$
$$
p = \frac{1}{n}\sum{x_i}
$$

## c.  Are either of these estimators unbiased forp?

Both of these are unbiased as the mean is unbiased for Bernoullirandom variables.

# 6. Chapter 6 Supplementary exercise # 32
## a.  LetX1,...,Xnbe a random sample from a uniform distribution on [0,θ].  (Here,θ >0.)  Then the MLE ofθisˆθ=Y= max{X1,...,Xn}.  (It takes some work toshow this is the MLE; the text discusses it in Example 6.22.  You are not asked toshow this; take it as a given.)  Show that the pdf ofY is

$$
f_Y(y) = \frac{ny^{n-1}}{\theta^n}
$$


## b. Use the result of part (a) to show that the MLE is biased, but y(n+1)/n is unbiased for Theta.

MLE is biased because it can never be above theta, but Y(n+1)/n is unbiased for Theta because it corrects for this bias.
# 7.  The birthday problem.  Mars experiences just under 667 Martian days and nights eachtime  it  revolves  around  the  sun.   Let’s  pretend  it’s  exactly  667  days.   Little  Martianfur-babies have birthdays that are uniformly distributed throughout the Martian year.LetEnbe the event that in a group ofnrandomly selected Martian fur-babies, no twoshare the same Martian birthday; i.e., all of them have distinct birthdays

## a. Find P(E2),  the probability that in a group of 2 randomly selected Martian fur-babies, the fur-babies have 2 distinct birthdays.

$$
1 - 1/667
$$

## b. FindP(E5).  FindP(EC5), the probability that in a group of 5 randomly selectedfur-babies, at least two will share the same birthday

$$
1-\frac{667}{667}*\frac{666}{667}*\frac{665}{667}*\frac{664}{667}*\frac{663}{667}=1-0.985 = 0.015
$$

## c.  Find the formula forP(En).
$$
P(E_n) = 1-\frac{\frac{667!}{(667-n)!}}{(667)^n} = 1-\frac{667!}{(667-n)!*667^n}
$$

# 8. (Extra credit) Referring to problem 7:  For which group sizen is P(ECn)>1/2?  In otherwords, how many fur-babies does it take before there’s a better than 50-50 chance that two or more of them will share the same birthday?

 It takes 31 babies for there to be a 50-50 chance that they will share the same birthday